# Generated by Django 3.1.2 on 2026-06-21 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=profiles.models.avatar_upload_path, verbose_name='Фото профиля')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('messenger', models.CharField(blank=True, max_length=100, null=True, verbose_name='Мессенджер')),
                ('extra_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Дополнительная почта')),
                ('show_phone', models.BooleanField(default=True, verbose_name='Показывать телефон')),
                ('show_messenger', models.BooleanField(default=True, verbose_name='Показывать мессенджер')),
                ('show_extra_email', models.BooleanField(default=True, verbose_name='Показывать доп. почту')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'profiles',
            },
        ),
    ]
