# Generated by Django 3.1.2 on 2020-10-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_history_history_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-history_date'], 'verbose_name': 'История изменений', 'verbose_name_plural': 'Истории изменений'},
        ),
    ]
