# Generated by Django 3.1.2 on 2020-10-23 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_subject', models.CharField(max_length=100, verbose_name='Тема заявки')),
                ('task_createdate', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('task_startdate', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('task_enddate', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания план')),
                ('task_fact_enddate', models.DateTimeField(blank=True, null=True, verbose_name='Дата фактического окончания')),
                ('task_prio', models.CharField(choices=[('CRIT', 'Критический'), ('HIGH', 'Высокий'), ('LOW', 'Низкий')], max_length=4, verbose_name='Приоритет')),
                ('task_status', models.CharField(choices=[('NEW', 'Новый'), ('CLOSE', 'Закрыт'), ('END', 'Предоставлен'), ('REQ', 'Запрос'), ('WORK', 'В работе'), ('ANS', 'Уточнен'), ('REF', 'Отклонен')], default='NEW', max_length=5, verbose_name='Статус')),
                ('task_text', models.TextField(verbose_name='Текст')),
                ('task_communication', models.CharField(choices=[('PHN', 'Телефон'), ('EML', 'Почта'), ('WEB', 'Веб'), ('BOT', 'Чат-бот')], default='WEB', max_length=5, verbose_name='Канал взаимодействия')),
                ('task_close', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('task_attention', models.BooleanField(default=False, verbose_name='Требует уточнения')),
                ('task_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('task_executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_file', models.FileField(upload_to=tasks.models.save_upload_file, verbose_name='Файл')),
                ('task_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'tasks_files',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Текст')),
                ('comment_createdate', models.DateTimeField(auto_now=True, verbose_name='Дата комментария')),
                ('comment_isresult', models.BooleanField(default=False, verbose_name='Решение')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('task_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Коментарии',
                'db_table': 'tasks_comments',
            },
        ),
    ]
