# Generated by Django 3.1.2 on 2020-10-23 11:34

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_uuid',
            field=models.CharField(default=tasks.models.random_uuid, max_length=32),
        ),
    ]
