# Generated by Django 3.1.2 on 2020-10-23 11:38

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_task_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_uuid',
            field=models.CharField(default=tasks.models.random_uuid, max_length=32, unique=True),
        ),
    ]
