# Generated by Django 3.1.2 on 2020-10-23 11:42

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201023_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_attention',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_uuid',
            field=models.CharField(default=tasks.models.random_uuid, max_length=12, unique=True),
        ),
    ]
