# Generated by Django 3.1.2 on 2020-10-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201023_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['comment_createdate'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
