# Generated by Django 3.1.2 on 2020-10-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201026_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-comment_createdate'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
