# Generated by Django 3.1.2 on 2020-10-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20201027_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_createdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
