# Generated by Django 3.1.2 on 2020-10-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20201028_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-comment_createdate', 'comment_isresult'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
