# Generated by Django 3.1.2 on 2020-10-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20201028_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-task_createdate'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-comment_isresult', '-comment_createdate'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
