# Generated by Django 3.1.2 on 2020-10-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20201028_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_communication',
            field=models.CharField(choices=[('PHN', 'Телефон'), ('EML', 'Почта'), ('WEB', 'Веб'), ('BOT', 'Чат-бот'), ('MSG', 'Мессенджер')], default='WEB', max_length=5, verbose_name='Канал взаимодействия'),
        ),
    ]
