# Generated by Django 3.1.2 on 2020-11-11 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('tasks', '0012_task_task_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_product',
            field=models.ForeignKey(blank=True, default=None, help_text='Компонент программного обеспечения', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='КПО'),
        ),
    ]
