# Generated by Django 3.1.2 on 2021-10-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20211021_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_createdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
