# Generated by Django 3.1.2 on 2021-10-21 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20211021_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_createdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='comment_createdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата комментария'),
        ),
    ]
