# Generated by Django 3.1.2 on 2026-06-21 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20260621_1701'),
        ('tasks', '0016_auto_20211021_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('solution_problem', models.TextField(verbose_name='Описание проблемы')),
                ('solution_text', models.TextField(verbose_name='Решение')),
                ('solution_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='КПО')),
            ],
            options={
                'verbose_name': 'Типовое решение',
                'verbose_name_plural': 'Типовые решения',
                'db_table': 'solutions',
            },
        ),
    ]
