# Generated by Django 3.1.2 on 2026-06-28 17:57

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='comment_file',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models.save_comment_file, verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='comment_text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
