# Generated by Django 3.1.2 on 2026-07-15 13:58

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_auto_20260628_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCommentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_file', models.FileField(upload_to=tasks.models.save_comment_attachment, verbose_name='Вложение')),
                ('comment_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.taskcomment')),
            ],
            options={
                'verbose_name': 'Вложение комментария',
                'verbose_name_plural': 'Вложения комментариев',
                'db_table': 'tasks_comment_files',
            },
        ),
    ]
